stages:
  - lint
  - build

lint:
  stage: lint
  script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ~/go/bin v1.49.0
    - ~/go/bin/golangci-lint --version
    - ~/go/bin/golangci-lint run

build:
  stage: build
  script:
    - echo $GOPATH
    - echo $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - go mod download
    - GOPRIVATE=gitlab.com CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o main
    - docker login registry.gitlab.com -u "${REPOSITORY_LOGIN}" -p "${REPOSITORY_PASSWORD}"
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --no-cache .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    variables:
      - '$CI_COMMIT_TAG != null'
